### PR TITLE
Issue 9 alt

### PR DESCRIPTION
**Pull request by zorkow**
Solves issue #9 and indirectly a number of other problems like #475

### CODE REVIEW

**Comment by pkra** [comment]
Very cool fix. Do they run in parallel now?

**Comment by zorkow** [comment]
> Very cool fix. Do they run in parallel now?

Yes, they do. And they share the same SRE build via a dependency. Still takes nearly an order of magnitude longer than on my home server. 
And there's too much redundant code. I am trying to simplify and move this into a common action right now.

**Comment by zorkow** [comment]
@pkra Now I am happy!

**Comment by pkra** [comment]
Very cool!

**Pull request merged**
