### PR TITLE
acss-fraction fix

### PR DESCRIPTION
**Pull request by tvraman**
Requesting a pull to zorkow:master from tvraman:acss-fraction
Trivial PR, mostly to test my end-to-end github workflow

### CODE REVIEW

**Comment by zorkow** [comment]
Can you make a PR into develop branch. Master branch is only for stable versions.

**Comment by tvraman** [comment]
sigh! could you just do a git pull <pr-url> this time?
--

**Comment by dpvc** [comment]
You should be able to use the "edit" button to the right of the PR title to edit the branch that the PR is targeted to merge into.  Since the branch is from `develop`, that should put everything into order.  You should inly see Raman's two commits at that point.

**Comment by dpvc** [comment]
@zorkow, I don't have write access to this repo, or I would have done it for you.  I think either you or @tvraman can do it.

**Comment by tvraman** [comment]
"Davide P. Cervone" <notifications@github.com> writes:

that "edit" button is what I'm trying to avoid.
My changes are trivial -- 2 char change:-)

will continue to noodle on this when I have time.
> You should be able to use the "edit" button to the right of the PR
> title to edit the branch that the PR is targeted to merge into. Since
> the branch is from develop, that should put everything into order. You
> should inly see Raman's two commits at that point.
>
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

--

**Comment by dpvc** [comment]
Sorry, I mac not have been clear.  The "edit" button I am talking about allows you to retarget the PR to a different branch (from `master` to `develop`).  It is not about editing the files within the PR.  It is a trivial thing, but I can't do it because I don't have write permission to the repository.  Volker should be able to do that for you.

**Comment by tvraman** [comment]
"Davide P. Cervone" <notifications@github.com> writes:

 I understand, for context, I'm trying to do this *without*  using a
 browser on github.com.

I think I just managed to push the pullreq to the develop branch.> Sorry, I mac not have been clear. The "edit" button I am talking about
> allows you to retarget the PR to a different branch (from master to
> develop). It is not about editing the files within the PR. It is a
> trivial thing, but I can't do it because I don't have write permission
> to the repository. Volker should be able to do that for you.
>
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

--

**Comment by dpvc** [comment]
> I'm trying to do this *without*  using a browser on github.com

Ah, sorry.  Now I understand.  Sorry to be a pest.

**Comment by zorkow** [comment]
Merged in PR #372

**Comment by zorkow** [comment]
Sorry I closed without seeing that I there has been a significant thread. 
Indeed I should have just rebased myself (I assume I could have done that). But honestly I was not aware of the little edit trick either. I usually just close and open a new PR. 
Thanks @dpvc, I shall remember that trick in the future.

**Comment by zorkow** [comment]
Of course now I can't change the base anymore, as the there are no diffs to develop. 
But it seems, like I could have done that too. 
Closing again.

**Pull request closed without merging**
